spring:
  application:
    name: aiplayground

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aiplayground}
    username: ${SPRING_DATASOURCE_USERNAME:devuser}
    password: ${SPRING_DATASOURCE_PASSWORD:devpassword}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: none  # Liquibase manages schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

logging:
  level:
    org.sualk.aiplayground: DEBUG
    org.hibernate.SQL: DEBUG
    liquibase: DEBUG
